server:
  port: 8080

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/localhost:3306/druidTest?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/